import os
from fastapi import FastAPI, HTTPException, status
from pydantic import BaseModel, Field
from dotenv import load_dotenv

# Explicitly load environment variables from the root backend/.env file
load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__), "..", ".env"))

# Import the LLM function from the week_2 module
from week_2.prompt_model import prompt_model

# Initialize the FastAPI application
app = FastAPI(
    title="LLM Chat Backend",
    description="A production-ready FastAPI service handling chat and PDF context injection.",
    version="1.0.0"
)

# Define the Pydantic request schema matching the frontend payload
class ChatRequest(BaseModel):
    message: str = Field(
        ..., 
        description="The user's text query string or question.",
        examples=["How does the internal bridge work in Docker?"]
    )
    pdf_text: str = Field(
        default="", 
        description="Extracted text string from the companion PDF, or an empty string if no file is uploaded.",
        examples=["Section 1.2: Network bridging protocols..."]
    )

@app.post(
    "/chat", 
    status_code=status.HTTP_200_OK,
    summary="Process Chat Message with PDF Context",
    response_description="The text response generated by the LLM."
)
async def chat_endpoint(payload: ChatRequest):
    """
    Asynchronous POST endpoint that receives a user message and optional PDF text context,
    passes them to the local LLM wrapper function, and returns the generated text.
    """
    try:
        # Extract fields securely from the validated payload
        user_message = payload.message
        # context_text = payload.pdf_text

        # Execute the LLM invocation function logic from week_2 module
        # This function utilizes the OLLAMA_HOST environment variable internally
        llm_output = prompt_model("gemini", user_message) # <------- Select model here
        
        # Structure and return the standard JSON response back to the client
        return {"response": llm_output}

    except Exception as e:
        # Gracefully handle internal wrapper or connection errors
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while communicating with the LLM layer: {str(e)}"
        )